// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function App(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setTodo = match[1];
  var todo = match[0];
  var match$1 = React.useState(function () {
        return [];
      });
  var setTodos = match$1[1];
  var todos = match$1[0];
  var onChange = function ($$event) {
    $$event.preventDefault();
    var value = $$event.target.value;
    return Curry._1(setTodo, (function (param) {
                  return value;
                }));
  };
  var todosList = Belt_Array.map(todos, (function (todo) {
          return React.createElement("li", {
                      key: todo
                    }, todo);
        }));
  var onClick = function (param) {
    return Curry._1(setTodos, (function (param) {
                  return todos.concat([todo]);
                }));
  };
  return React.createElement("div", undefined, React.createElement("input", {
                  value: todo,
                  onChange: onChange
                }), React.createElement("button", {
                  onClick: onClick
                }, "Submit"), React.createElement("ul", undefined, todosList));
}

var make = App;

exports.make = make;
/* react Not a pure module */
