// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var App = require("./App.bs.js");
var React = require("react");
var ReactDom = require("react-dom");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

ReactDom.render(React.createElement(App.make, {}), Belt_Option.getExn(Caml_option.nullable_to_opt(document.querySelector("#root"))));

/*  Not a pure module */
